[build]
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# A redirect rule with many of the supported properties
[[redirects]]
  from = "/"
  to = "/docs"

  # By default, redirects won’t be applied if there’s a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  force = true

# This path was accidentally used in the public announcement email
[[redirects]]
  from = "/docs/user-guide/automatic-inline-seeding-user-guide"
  to = "/docs/user-guide/automatic-inline-seeds"
  status = 301

# This path was accidentally used in the internal announcement email
[[redirects]]
  from = "/docs/user-guide/automatic-inline-seeding"
  to = "/docs/user-guide/automatic-inline-seeds"
  status = 301